# Generated by Django 5.1.2 on 2025-04-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اللوحة')),
                ('description', models.TextField(verbose_name='وصف اللوحة')),
                ('image', models.ImageField(upload_to='paints/', verbose_name='صورة اللوحة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
        ),
    ]
